### ISSUE TITLE
Add an option to hide timestamp

### ISSUE THREAD

**Issue by Corjen** [Kentico/kontent-model-generator-js#1]
### Motivation

Why is this feature required? What problems does it solve?

Hi! We'd like to check in the generated models into our repo. When generating, the cli prints a line with the generation time, e.g.: `Timestamp: Wed Feb 12 2020 08:55:07 GMT+0100 (Central European Standard Time)`. This causes merge conflicts between different pr's, eventhough the actual model hasn't change. 

### Proposed solution 

We would like to add a flag to to the cli, something like `--skipTimestamp`, which would simply skip printing the line with the time. I'd be happy to send a PR for that sometime next week if it's something you would see merged.

**Comment by Enngage** [comment]
Hey,

Yeah, that makes sense. I've modified the code accordingly so that you can now use `addTimestamp` configuration option. It's a boolean so set it to false. 

I've released `3.2.0` with this change. 

Hope that helps!

**Comment by Corjen** [comment]
Wow, that’s really fast. Thanks!👏
