### ISSUE TITLE
Generating models fails - Type 'IContentItem' is not generic.ts

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-model-generator-js#20]
### Brief bug description

I have generated the models and they looks as described in readme.

```ts
import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0' at 'Tue, 23 Nov 2021 17:18:24 GMT'
 */
export type Stat = IContentItem<{
  link_text: Elements.TextElement;
  metric: Elements.TextElement;
  link_url: Elements.TextElement;
  description: Elements.TextElement;
  note: Elements.TextElement;
}>;
```

 But my compiler is complaining: 
 ```
Type 'IContentItem' is not generic.ts(2315)
(alias) interface IContentItem
import IContentItem
```

### Repro steps

1. Generate any model
2. Run TS compilation/lint

### Expected behavior

No error should be raised.

### Screenshots

![image](https://user-images.githubusercontent.com/9218736/143075345-3eac0de6-5700-4b87-a106-149b075ddf15.png)

**Comment by Enngage** [comment]
@Simply007 As this is only generator, it does not provide `IContentItem` interface. Does your repo have Delivery JS SDK on version `11.0.0` installed?

**Comment by Simply007** [comment]
> @Simply007 As this is only generator, it does not provide `IContentItem` interface. Does your repo have Delivery JS SDK on version `11.0.0` installed?

My fault!

I have set the SDK version to v11, removed package-lock.json, and ran `npm install`. Unfortunately, I haven't saved the packege.json 🤦‍♂️
