### ISSUE TITLE
Support for Content type snippets

### ISSUE THREAD

**Issue by cwaespi** [Kentico/kontent-model-generator-js#24]
### Motivation

In version 5.0.0-1, types are no longer generated for the **Content type snippets**.

### Proposed solution

Generate type for **Content type snippets**.

### Additional context

![image](https://user-images.githubusercontent.com/14320406/169798142-bd73dbad-0c37-4247-9b63-ae83c89fb2bb.png)

The yellow marked properties are missing in type generation.

**Comment by Enngage** [comment]
Thank you for letting me know @cwaespi. I'll have a look at this.

**Comment by Enngage** [comment]
Content type snippet elements should be available in version `5.0.0-2` ;) Let me know if you encounter any other issues as this is a pre-release and we might still change some things before major release.

**Comment by cwaespi** [comment]
@Enngage cool thx for the quick realization.

There is one issue I noticed while check the new version. The import statement for  `LinkedItemsElement` types are missing in content-type files.

![image](https://user-images.githubusercontent.com/14320406/170113174-d4cb8bbb-14c1-48a5-9903-d70ca0925cf1.png)

**Comment by Enngage** [comment]
Hey @cwaespi, thanks for letting me know! The imports should be fixed in version `5.0.0-3`. Feel free to let me know if you encounter any other issues ;)
