### ISSUE TITLE
Ability to add prefix to generated classes

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/kontent-model-generator-js#7]
### Motivation

I'd like to be able to use the generated classes as base classes that I extend from rather than modify the generated files. This way it's easier to regenerate at any time with changes.

### Proposed solution

It would be nice to be able to specify a prefix or suffix for the generated classes. For example: `BaseActor` or `ActorGenerated` so that I can create a calls `Actor` that extends the generated one. It would also be useful for avoiding clashes with things that already exist in a framework (e.g. `Page` could become `KontentPage`)

**Comment by Enngage** [comment]
New version of Delivery SDK is using models differently and it is no longer possible to "extend" a model class because there simply isn't any class ;) Strongly typed models provide typings for elements only and there will always only be these elements.
